<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        
        $customers = [
            // Hospitals (HighValue)
            [
                'Institution_Name' => 'Metro Manila General Hospital',
                'Customer_Type' => 'Hospital',
                'Contact_Person' => 'Dr. Roberto Santos',
                'Email' => 'dr.santos@mmgh.ph',
                'Phone' => '+63 2 8888 1111',
                'Address' => '789 Hospital Road, Manila City 1000',
                'Segment_Type' => 'HighValue',
                'Status' => 'Active',
                'Credit_Limit' => 2000000.00,
                'Available_Credit' => 150000.00,
                'Payment_Terms_Preference' => '30 days',
                'Total_Purchase_Value' => 1850000.00,
                'Last_Interaction_Date' => $now->subDays(5),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'St. Luke\'s Medical Center - Global City',
                'Customer_Type' => 'Hospital',
                'Contact_Person' => 'Dr. Maria Gonzales',
                'Email' => 'm.gonzales@stlukes.com',
                'Phone' => '+63 2 8888 2222',
                'Address' => '32nd Street, Bonifacio Global City, Taguig 1634',
                'Segment_Type' => 'HighValue',
                'Status' => 'Active',
                'Credit_Limit' => 3000000.00,
                'Available_Credit' => 250000.00,
                'Payment_Terms_Preference' => '60 days',
                'Total_Purchase_Value' => 2750000.00,
                'Last_Interaction_Date' => $now->subDays(12),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'Asian Hospital and Medical Center',
                'Customer_Type' => 'Hospital',
                'Contact_Person' => 'Mr. Henry Lim',
                'Email' => 'h.lim@asianhospital.com',
                'Phone' => '+63 2 8888 3333',
                'Address' => '2205 Civic Drive, Filinvest City, Alabang, Muntinlupa 1780',
                'Segment_Type' => 'HighValue',
                'Status' => 'Active',
                'Credit_Limit' => 1500000.00,
                'Available_Credit' => 250000.00,
                'Payment_Terms_Preference' => '45 days',
                'Total_Purchase_Value' => 1250000.00,
                'Last_Interaction_Date' => $now->subDays(20),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Schools & Universities
            [
                'Institution_Name' => 'University of Santo Tomas - College of Nursing',
                'Customer_Type' => 'School',
                'Contact_Person' => 'Prof. Jose Reyes',
                'Email' => 'jose.reyes@ust.edu.ph',
                'Phone' => '+63 2 8888 4444',
                'Address' => 'España Boulevard, Sampaloc, Manila 1015',
                'Segment_Type' => 'MediumValue',
                'Status' => 'Active',
                'Credit_Limit' => 500000.00,
                'Available_Credit' => 50000.00,
                'Payment_Terms_Preference' => '30 days',
                'Total_Purchase_Value' => 450000.00,
                'Last_Interaction_Date' => $now->subDays(8),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'Ateneo de Manila University - School of Medicine',
                'Customer_Type' => 'School',
                'Contact_Person' => 'Dr. Lisa Tan',
                'Email' => 'l.tan@ateneo.edu',
                'Phone' => '+63 2 8888 5555',
                'Address' => 'Katipunan Avenue, Loyola Heights, Quezon City 1108',
                'Segment_Type' => 'MediumValue',
                'Status' => 'Active',
                'Credit_Limit' => 500000.00,
                'Available_Credit' => 180000.00,
                'Payment_Terms_Preference' => '30 days',
                'Total_Purchase_Value' => 320000.00,
                'Last_Interaction_Date' => $now->subDays(15),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Government Agencies
            [
                'Institution_Name' => 'Department of Health - Central Office',
                'Customer_Type' => 'Government',
                'Contact_Person' => 'Dir. Carlos Mendoza',
                'Email' => 'c.mendoza@doh.gov.ph',
                'Phone' => '+63 2 8888 6666',
                'Address' => 'San Lazaro Compound, Tayuman, Sta. Cruz, Manila 1003',
                'Segment_Type' => 'HighValue',
                'Status' => 'Active',
                'Credit_Limit' => 5000000.00,
                'Available_Credit' => 5000000.00,
                'Payment_Terms_Preference' => '90 days',
                'Total_Purchase_Value' => 0.00,
                'Last_Interaction_Date' => $now->subDays(3),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'Philippine General Hospital',
                'Customer_Type' => 'Government',
                'Contact_Person' => 'Dr. Susan Cruz',
                'Email' => 's.cruz@pgh.gov.ph',
                'Phone' => '+63 2 8888 7777',
                'Address' => 'Taft Avenue, Ermita, Manila 1000',
                'Segment_Type' => 'HighValue',
                'Status' => 'Active',
                'Credit_Limit' => 2000000.00,
                'Available_Credit' => 150000.00,
                'Payment_Terms_Preference' => '60 days',
                'Total_Purchase_Value' => 1850000.00,
                'Last_Interaction_Date' => $now->subMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Private Clinics
            [
                'Institution_Name' => 'Mercury Diagnostic and Wellness Clinic',
                'Customer_Type' => 'PrivateClinic',
                'Contact_Person' => 'Dr. Antonio Lopez',
                'Email' => 'info@mercurydiagnostic.com',
                'Phone' => '+63 2 8888 8888',
                'Address' => '789 Clinic Street, Salcedo Village, Makati City 1227',
                'Segment_Type' => 'MediumValue',
                'Status' => 'Active',
                'Credit_Limit' => 100000.00,
                'Available_Credit' => 100000.00,
                'Payment_Terms_Preference' => '15 days',
                'Total_Purchase_Value' => 0.00,
                'Last_Interaction_Date' => $now->subDays(2),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'Wellness Medical Center - Pasig',
                'Customer_Type' => 'PrivateClinic',
                'Contact_Person' => 'Dr. Elena Torres',
                'Email' => 'e.torres@wellnessmed.com',
                'Phone' => '+63 2 8888 9999',
                'Address' => '234 Wellness Boulevard, Ortigas Center, Pasig City 1605',
                'Segment_Type' => 'MediumValue',
                'Status' => 'Active',
                'Credit_Limit' => 500000.00,
                'Available_Credit' => 315000.00,
                'Payment_Terms_Preference' => '30 days',
                'Total_Purchase_Value' => 185000.00,
                'Last_Interaction_Date' => $now->subDays(25),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Prospects
            [
                'Institution_Name' => 'New Life Birthing and Maternity Clinic',
                'Customer_Type' => 'PrivateClinic',
                'Contact_Person' => 'Ms. Jennifer Sy',
                'Email' => 'jennifer@newlifeclinic.ph',
                'Phone' => '+63 917 111 2222',
                'Address' => '123 New Life Street, Marikina City 1800',
                'Segment_Type' => 'Prospect',
                'Status' => 'Active',
                'Credit_Limit' => 0.00,
                'Available_Credit' => 0.00,
                'Payment_Terms_Preference' => 'TBD',
                'Total_Purchase_Value' => 0.00,
                'Last_Interaction_Date' => $now->subDays(7),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Institution_Name' => 'Hope Community Hospital - Bulacan',
                'Customer_Type' => 'Hospital',
                'Contact_Person' => 'Dr. Benjamin Ong',
                'Email' => 'b.ong@hopehospital.ph',
                'Phone' => '+63 44 777 8888',
                'Address' => '456 Hope Avenue, Balagtas, Bulacan 3016',
                'Segment_Type' => 'Prospect',
                'Status' => 'Active',
                'Credit_Limit' => 0.00,
                'Available_Credit' => 0.00,
                'Payment_Terms_Preference' => 'TBD',
                'Total_Purchase_Value' => 0.00,
                'Last_Interaction_Date' => $now->subDays(10),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('customers')->insert($customers);
        $this->command->info('✅ Seeded 11 customers');
    }
}