<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        
        $products = [
            // Hospital Equipment (Category 1) -> DiagnosticEquipment
            [
                'Product_Code' => 'PM-001',
                'Product_Name' => 'Multi-Parameter Patient Monitor - 5-in-1',
                'Description' => 'Advanced patient monitor with ECG, SPO2, NIBP, Temperature, and Respiration monitoring. Features 12.1" color LCD, WiFi connectivity, and 4-hour battery backup.',
                'Category' => 'DiagnosticEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 24,
                'Warranty_Terms' => 'Replacement for factory defects. 2 years parts and service.',
                'Weight_KG' => 4.50,
                'Length_CM' => 32.00,
                'Width_CM' => 28.00,
                'Height_CM' => 12.00,
                'Specifications' => json_encode([
                    'Display' => '12.1" Color LCD Touchscreen',
                    'Parameters' => 'ECG, SPO2, NIBP, Temp, Resp',
                    'Battery' => '4 hours backup',
                    'Connectivity' => 'WiFi, Ethernet, USB',
                ]),
                'Images_Path' => 'products/patient_monitor.jpg',
                'Unit_Price_PHP' => 85000.00,
                'Unit_Price_USD' => 1491.23,
                'Min_Stock_Level' => 3,
                'Reorder_Quantity' => 5,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'SP-001',
                'Product_Name' => 'Syringe Infusion Pump with DERS',
                'Description' => 'Precision syringe infusion pump with Dose Error Reduction System. Supports 1ml to 60ml syringes with ±2% accuracy.',
                'Category' => 'MedicalInstruments',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year limited warranty.',
                'Weight_KG' => 3.20,
                'Length_CM' => 25.00,
                'Width_CM' => 15.00,
                'Height_CM' => 10.00,
                'Specifications' => json_encode([
                    'Type' => 'Syringe Pump',
                    'Flow Rate' => '0.1 ml/h to 1200 ml/h',
                    'Syringe Sizes' => '1ml, 5ml, 10ml, 20ml, 30ml, 50ml, 60ml',
                    'Accuracy' => '±2%',
                ]),
                'Images_Path' => 'products/infusion_pump.jpg',
                'Unit_Price_PHP' => 45000.00,
                'Unit_Price_USD' => 789.47,
                'Min_Stock_Level' => 5,
                'Reorder_Quantity' => 10,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'US-001',
                'Product_Name' => 'Portable Color Doppler Ultrasound System',
                'Description' => 'Digital color Doppler ultrasound with convex and linear probes. Perfect for abdominal, OB/GYN, and cardiac imaging.',
                'Category' => 'DiagnosticEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 36,
                'Warranty_Terms' => '3 years comprehensive warranty.',
                'Weight_KG' => 8.50,
                'Length_CM' => 40.00,
                'Width_CM' => 35.00,
                'Height_CM' => 15.00,
                'Specifications' => json_encode([
                    'Probes' => 'Convex 3.5MHz, Linear 7.5MHz',
                    'Display' => '15.6" LED Touchscreen',
                    'Imaging Modes' => 'B-mode, M-mode, Color Doppler, Pulse Wave',
                ]),
                'Images_Path' => 'products/ultrasound.jpg',
                'Unit_Price_PHP' => 350000.00,
                'Unit_Price_USD' => 6140.35,
                'Min_Stock_Level' => 2,
                'Reorder_Quantity' => 3,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Pharmacy Supplies (Category 2) -> PharmacySupplies
            [
                'Product_Code' => 'FR-001',
                'Product_Name' => 'Pharmacy-Grade Medicine Refrigerator',
                'Description' => 'Medical refrigerator with digital temperature control and alarm system. Ideal for vaccines and temperature-sensitive medications.',
                'Category' => 'LaboratoryEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year warranty on compressor.',
                'Weight_KG' => 85.00,
                'Length_CM' => 185.00,
                'Width_CM' => 65.00,
                'Height_CM' => 70.00,
                'Specifications' => json_encode([
                    'Capacity' => '300 liters',
                    'Temperature Range' => '2°C to 8°C',
                ]),
                'Images_Path' => 'products/medicine_fridge.jpg',
                'Unit_Price_PHP' => 65000.00,
                'Unit_Price_USD' => 1140.35,
                'Min_Stock_Level' => 4,
                'Reorder_Quantity' => 8,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'TC-001',
                'Product_Name' => 'Automatic Tablet & Capsule Counting Machine',
                'Description' => 'High-speed automatic pill counter with 99.9% accuracy. Touchscreen interface with batch counting capability.',
                'Category' => 'LaboratoryEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year parts and service.',
                'Weight_KG' => 15.00,
                'Length_CM' => 45.00,
                'Width_CM' => 40.00,
                'Height_CM' => 60.00,
                'Specifications' => json_encode([
                    'Speed' => '2000 pills per minute',
                    'Accuracy' => '99.9%',
                    'Hopper Capacity' => '5 liters',
                    'Display' => '7" Touchscreen',
                ]),
                'Images_Path' => 'products/pill_counter.jpg',
                'Unit_Price_PHP' => 120000.00,
                'Unit_Price_USD' => 2105.26,
                'Min_Stock_Level' => 2,
                'Reorder_Quantity' => 4,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Hospital Furniture (Category 3) -> HospitalFurniture
            [
                'Product_Code' => 'HB-001',
                'Product_Name' => 'Full Electric Hospital Bed - ICU Model',
                'Description' => 'ICU-grade electric hospital bed with Trendelenburg, CPR, and cardiac chair functions. Includes anti-decubitus mattress.',
                'Category' => 'MedicalInstruments',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year electronics warranty.',
                'Weight_KG' => 150.00,
                'Length_CM' => 218.00,
                'Width_CM' => 106.00,
                'Height_CM' => 50.00,
                'Specifications' => json_encode([
                    'Functions' => 'Trendelenburg, Reverse Trendelenburg, CPR, Cardiac Chair',
                ]),
                'Images_Path' => 'products/hospital_bed.jpg',
                'Unit_Price_PHP' => 95000.00,
                'Unit_Price_USD' => 1666.67,
                'Min_Stock_Level' => 4,
                'Reorder_Quantity' => 8,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'SP-002',
                'Product_Name' => 'Portable Manual Suction Pump',
                'Description' => 'Emergency manual suction unit for airway management. Portable and reliable for ambulance or clinic use.',
                'Category' => 'MedicalInstruments',
                'Status' => 'Active',
                'Warranty_Months' => 6,
                'Warranty_Terms' => '6 months limited warranty.',
                'Weight_KG' => 3.20,
                'Length_CM' => 30.00,
                'Width_CM' => 20.00,
                'Height_CM' => 15.00,
                'Specifications' => json_encode([
                    'Type' => 'Manual, piston-operated',
                    'Pressure' => '0 to 600 mmHg',
                    'Collection Bottle' => '1000 ml disposable',
                ]),
                'Images_Path' => 'products/suction_pump.jpg',
                'Unit_Price_PHP' => 8500.00,
                'Unit_Price_USD' => 149.12,
                'Min_Stock_Level' => 10,
                'Reorder_Quantity' => 20,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // EMS Equipment (Category 4) -> EmergencySupplies
            [
                'Product_Code' => 'DF-001',
                'Product_Name' => 'Manual/AED Defibrillator with Pacing',
                'Description' => 'Professional defibrillator with AED and manual modes. Includes ECG monitoring, pacing, and SPO2 capability.',
                'Category' => 'EmergencyEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 24,
                'Warranty_Terms' => '2 years factory warranty.',
                'Weight_KG' => 4.80,
                'Length_CM' => 30.00,
                'Width_CM' => 25.00,
                'Height_CM' => 20.00,
                'Specifications' => json_encode([
                    'Modes' => 'AED, Manual, Monitor, Pacing',
                    'Energy Levels' => '2-200 Joules (biphasic)',
                ]),
                'Images_Path' => 'products/defibrillator.jpg',
                'Unit_Price_PHP' => 250000.00,
                'Unit_Price_USD' => 4385.96,
                'Min_Stock_Level' => 2,
                'Reorder_Quantity' => 4,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'VE-001',
                'Product_Name' => 'Transport Emergency Ventilator',
                'Description' => 'Compact transport ventilator with multiple ventilation modes. Ideal for ICU transport and emergency response.',
                'Category' => 'EmergencyEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 24,
                'Warranty_Terms' => '2 years comprehensive.',
                'Weight_KG' => 6.50,
                'Length_CM' => 35.00,
                'Width_CM' => 28.00,
                'Height_CM' => 20.00,
                'Specifications' => json_encode([
                    'Modes' => 'CMV, SIMV, PSV, CPAP',
                    'Rate' => '5 to 60 breaths/min',
                    'Tidal Volume' => '50 to 2000 ml',
                ]),
                'Images_Path' => 'products/ventilator.jpg',
                'Unit_Price_PHP' => 180000.00,
                'Unit_Price_USD' => 3157.89,
                'Min_Stock_Level' => 3,
                'Reorder_Quantity' => 6,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Laboratory Equipment (Category 5) -> LabEquipment
            [
                'Product_Code' => 'CE-001',
                'Product_Name' => 'Refrigerated Centrifuge Machine',
                'Description' => 'Digital refrigerated centrifuge for laboratory use. Temperature control from -20°C to +40°C.',
                'Category' => 'LaboratoryEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year warranty.',
                'Weight_KG' => 45.00,
                'Length_CM' => 60.00,
                'Width_CM' => 50.00,
                'Height_CM' => 45.00,
                'Specifications' => json_encode([
                    'Max Speed' => '6000 rpm',
                    'Capacity' => '48 x 15ml tubes',
                ]),
                'Images_Path' => 'products/centrifuge.jpg',
                'Unit_Price_PHP' => 75000.00,
                'Unit_Price_USD' => 1315.79,
                'Min_Stock_Level' => 3,
                'Reorder_Quantity' => 6,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'Product_Code' => 'AS-001',
                'Product_Name' => 'Digital Autoclave Sterilizer',
                'Description' => 'Class B autoclave for medical instrument sterilization. Automatic cycles with printer output.',
                'Category' => 'LaboratoryEquipment',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year parts.',
                'Weight_KG' => 35.00,
                'Length_CM' => 55.00,
                'Width_CM' => 45.00,
                'Height_CM' => 40.00,
                'Specifications' => json_encode([
                    'Chamber Size' => '23 liters',
                    'Temperature' => '121°C to 134°C',
                ]),
                'Images_Path' => 'products/autoclave.jpg',
                'Unit_Price_PHP' => 125000.00,
                'Unit_Price_USD' => 2192.98,
                'Min_Stock_Level' => 2,
                'Reorder_Quantity' => 4,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Dental Equipment (Category 6) -> DentalSupply
            [
                'Product_Code' => 'DC-001',
                'Product_Name' => 'Dental Chair Unit with X-ray',
                'Description' => 'Complete dental chair unit with integrated X-ray and handpieces. LED lighting and assistant module included.',
                'Category' => 'MedicalInstruments',
                'Status' => 'Active',
                'Warranty_Months' => 12,
                'Warranty_Terms' => '1 year parts and service warranty.',
                'Weight_KG' => 280.00,
                'Length_CM' => 180.00,
                'Width_CM' => 120.00,
                'Height_CM' => 150.00,
                'Specifications' => json_encode([
                    'Chair Movements' => 'Electric, programmable positions',
                ]),
                'Images_Path' => 'products/dental_chair.jpg',
                'Unit_Price_PHP' => 450000.00,
                'Unit_Price_USD' => 7894.74,
                'Min_Stock_Level' => 1,
                'Reorder_Quantity' => 2,
                'FDA_Certification_Status' => 'Certified',
                'Supplier_ID' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('products')->insert($products);
        $this->command->info('✅ Seeded ' . count($products) . ' products');

        
    }
}